### ISSUE TITLE
ロード中に例外が起きる場合がある

### ISSUE THREAD

**Issue by alterakey** [alterakey/lucene#1]
```
W/dalvikvm( 4723): threadid=18: thread exiting with uncaught exception (group=0x40a311f8)
E/AndroidRuntime( 4723): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 4723): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 4723):    at android.os.AsyncTask$3.done(AsyncTask.java:278)
E/AndroidRuntime( 4723):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime( 4723):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime( 4723):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime( 4723):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime( 4723):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 4723):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 4723):    at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime( 4723): Caused by: java.lang.OutOfMemoryError
E/AndroidRuntime( 4723):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/AndroidRuntime( 4723):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:493)
E/AndroidRuntime( 4723):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:549)
E/AndroidRuntime( 4723):    at android.graphics.drawable.BitmapDrawable.<init>(BitmapDrawable.java:157)
E/AndroidRuntime( 4723):    at com.gmail.altakey.lucene.AsyncImageLoader.doInBackground(AsyncImageLoader.java:84)
E/AndroidRuntime( 4723):    at com.gmail.altakey.lucene.AsyncImageLoader.doInBackground(AsyncImageLoader.java:18)
E/AndroidRuntime( 4723):    at android.os.AsyncTask$2.call(AsyncTask.java:264)
E/AndroidRuntime( 4723):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime( 4723):    ... 4 more
W/ActivityManager(  128):   Force finishing activity com.gmail.altakey.lucene/.ViewActivity
...
E/WindowManager( 4723): android.view.WindowLeaked: Activity com.gmail.altakey.lucene.ViewActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@41445a28 that was originally added here
E/WindowManager( 4723):     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:343)
E/WindowManager( 4723):     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:245)
E/WindowManager( 4723):     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:193)
E/WindowManager( 4723):     at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:118)
E/WindowManager( 4723):     at android.view.Window$LocalWindowManager.addView(Window.java:537)
E/WindowManager( 4723):     at android.app.Dialog.show(Dialog.java:274)
E/WindowManager( 4723):     at com.gmail.altakey.lucene.AsyncImageLoader.onPreExecute(AsyncImageLoader.java:55)
E/WindowManager( 4723):     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:561)
E/WindowManager( 4723):     at android.os.AsyncTask.execute(AsyncTask.java:511)
E/WindowManager( 4723):     at com.gmail.altakey.lucene.ViewActivity.onCreate(ViewActivity.java:61)
E/WindowManager( 4723):     at android.app.Activity.performCreate(Activity.java:4465)
E/WindowManager( 4723):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
E/WindowManager( 4723):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1919)
E/WindowManager( 4723):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1980)
E/WindowManager( 4723):     at android.app.ActivityThread.access$600(ActivityThread.java:122)
E/WindowManager( 4723):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1146)
E/WindowManager( 4723):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/WindowManager( 4723):     at android.os.Looper.loop(Looper.java:137)
E/WindowManager( 4723):     at android.app.ActivityThread.main(ActivityThread.java:4340)
E/WindowManager( 4723):     at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager( 4723):     at java.lang.reflect.Method.invoke(Method.java:511)
E/WindowManager( 4723):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/WindowManager( 4723):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/WindowManager( 4723):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by alterakey** [comment]
メモリ

**Comment by alterakey** [comment]
それにしてもこれはみっともないので何か考えよう…

**Comment by alterakey** [comment]
blitzで修正。
